# Lab 3 - Group E1

## Question 1

## Question 2

In [90]:
import statistics as st
import numpy as np
import scipy.linalg as la
from datetime import datetime
import sympy as sym

cov = np.array([[2, -1, 0],
                [-1, 2, -1],
                [0, -1, 2]]);
mu = np.array([1,3,-5]);

def posSymDef(mat):
    return np.all(np.linalg.eigvals(mat) > 0)

def diagonal(matrix):
    eigval,m1 = la.eig(matrix);    
    m1 = np.array(m1).astype(float);
    m1_inv = np.linalg.inv(m1);
    m2 = np.matmul(m1_inv,matrix);
    m2 = np.matmul(m2,m1);
    return m2,m1;

def func(mu,cov,s):
    m2,m1 = diagonal(cov);
    m1 = np.array(m1).astype(float);
    m2 = np.array(m2).astype(float);
    m1_inv = np.linalg.inv(m1);
    for i in range(len(m2)):
        m2[i][i] = np.sqrt(m2[i][i]);
    M = np.matmul(m1,m2);
    M = np.matmul(M,m1_inv);
    ans = np.matmul(np.random.randn(s, len(m2)),M);
    for i in range(s):
        ans[i] = ans[i] + mu;
    print('\nSamples:');
    print(ans);
    print('\nMean Vector:');
    mu = [];
    ans = np.transpose(ans);
    for i in range(len(m2)): 
        mu.append(np.mean(ans[i]));
    print(mu);
    print('\nCovariance Matrix:');
    print(np.cov(ans));
    print('\nCalculated matrix SPD?: '+str(posSymDef(cov)));

print('\nEntered Mean vector:');
print(mu);
print('\nEntered Covariance matrix:');
print(cov);

func(mu,cov,10000);


Entered Mean vector:
[ 1  3 -5]

Entered Covariance matrix:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

Samples:
[[ 1.17127078  2.33267287 -4.66581443]
 [ 0.02859858  4.39143558 -5.06485737]
 [ 2.69255431  2.70787126 -4.53182122]
 ...
 [ 0.99227373  3.3472687  -4.48434472]
 [ 1.21771357  1.59680927 -3.72639487]
 [ 1.33471066  2.33941866 -2.89447428]]

Mean Vector:
[1.002842416345811, 2.985555097041004, -4.986957028962303]

Covariance Matrix:
[[ 1.95474691 -0.98686334 -0.00235431]
 [-0.98686334  2.02356124 -0.99387325]
 [-0.00235431 -0.99387325  2.01790736]]

Calculated matrix SPD?: True
